services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    volumes:
      - uploads_data:/app/public/uploads
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://187.77.217.145:3000
        NEXT_PUBLIC_FRONTEND_URL: http://187.77.217.145:3001
    restart: unless-stopped
    ports:
      - "3001:3001"
    depends_on:
      - backend
    extra_hosts:
      - "host.docker.internal:host-gateway"

  omr_service:
    build:
      context: ./omr_service
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "5000:5000"

volumes:
  uploads_data:
